# git-cliff configuration for tesseras-net
# https://git-cliff.org/docs/configuration

[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).\n
"""

body = """
{%- macro remote_url() -%}
  https://git.sr.ht/~ijanc/tesseras-net
{%- endmacro -%}

{% if version -%}
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
    ## [Unreleased]
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}**{{ commit.scope }}:** {% endif %}\
            {% if commit.breaking %}[**BREAKING**] {% endif %}\
            {{ commit.message | upper_first }}\
            {%- if commit.links %} \
                ({{ commit.links | join(sep=", ") }})\
            {%- endif %}
    {%- endfor %}
{% endfor %}
"""

footer = """
{%- macro remote_url() -%}
  https://git.sr.ht/~ijanc/tesseras-net
{%- endmacro -%}

{% for release in releases -%}
    {% if release.version -%}
        {% if release.previous.version -%}
            [{{ release.version | trim_start_matches(pat="v") }}]: \
                {{ self::remote_url() }}/compare/{{ release.previous.version }}...{{ release.version }}
        {% endif -%}
    {% else -%}
        {% if release.previous.version -%}
            [Unreleased]: {{ self::remote_url() }}/compare/{{ release.previous.version }}...HEAD
        {% endif -%}
    {% endif -%}
{% endfor %}
"""

trim = true

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
protect_breaking_commits = true
filter_commits = false
topo_order = false
sort_commits = "newest"
tag_pattern = "v[0-9].*"

commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->Features" },
  { message = "^fix", group = "<!-- 1 -->Bug Fixes" },
  { message = "^perf", group = "<!-- 2 -->Performance" },
  { message = "^refactor", group = "<!-- 3 -->Refactoring" },
  { message = "^doc", group = "<!-- 4 -->Documentation" },
  { message = "^test", group = "<!-- 5 -->Testing" },
  { message = "^audit", group = "<!-- 6 -->Security & Auditing" },
  { message = "^style", group = "<!-- 7 -->Styling" },
  { message = "^chore", group = "<!-- 8 -->Miscellaneous" },
  { message = "^ci", group = "<!-- 8 -->Miscellaneous" },
  { message = "^build", group = "<!-- 8 -->Miscellaneous" },
]

link_parsers = [
  { pattern = "#(\\d+)", href = "https://git.sr.ht/~ijanc/tesseras-net/issues/$1" },
]
